// Centralized SEO config — change SITE here once.
export const SITE = "https://fishxcode-gpt-image-2.lovable.app";

// Owner-provided search-engine verification tokens (optional).
// Replace with real values once issued from Google Search Console / Bing Webmaster Tools.
export const VERIFICATION = {
  google: "REPLACE_WITH_GOOGLE_VERIFICATION_TOKEN",
  bing: "REPLACE_WITH_BING_VERIFICATION_TOKEN",
};

export type RouteSeo = {
  path: string; // canonical path (no trailing slash except "/")
  zh: { title: string; description: string };
  en: { title: string; description: string };
};

export const ROUTES_SEO: RouteSeo[] = [
  {
    path: "/",
    zh: {
      title: "GPT-Image-2 工具站 — 在线 AI 图像生成 Playground",
      description:
        "在线调用 gpt-image-2 接口生成与解析图像，支持自定义 API、参数、多语言（中/英）与可分享链接。所有 Key 仅保存在浏览器本地。",
    },
    en: {
      title: "GPT-Image-2 Tools — Online AI Image Generation Playground",
      description:
        "Online playground for the gpt-image-2 image-generation endpoint with custom API, params, i18n and shareable links. Your key never leaves the browser.",
    },
  },
  {
    path: "/prompts",
    zh: {
      title: "提示词广场 · GPT-Image-2 高质量 Prompt 精选",
      description:
        "精选 gpt-image-2 高质量提示词，涵盖人像、产品、场景、艺术等分类。一键复制并直接在 Playground 中生成图像。",
    },
    en: {
      title: "Prompt Plaza · Curated GPT-Image-2 Prompts",
      description:
        "Hand-picked high-quality prompts for gpt-image-2 across portrait, product, scene and art categories. One-click copy and run in the Playground.",
    },
  },
  {
    path: "/gallery",
    zh: {
      title: "素材广场 · GPT-Image-2 示例图像与可复用 Prompt",
      description:
        "浏览 gpt-image-2 生成的示例素材，查看背后的 prompt 与参数，并一键复用到 Playground。",
    },
    en: {
      title: "Asset Gallery · GPT-Image-2 Showcase & Reusable Prompts",
      description:
        "Browse showcase assets generated by gpt-image-2, inspect their prompts and parameters, and reuse them in the Playground in one click.",
    },
  },
];

export function getRouteSeo(path: string): RouteSeo {
  return ROUTES_SEO.find((r) => r.path === path) ?? ROUTES_SEO[0];
}

export function ogImageFor(lang: "zh" | "en") {
  return `${SITE}/og-${lang}.png`;
}
