/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as ApiRssDotxmlRouteImport } from './routes/api/rss[.]xml'
import { Route as ApiRobotsDottxtRouteImport } from './routes/api/robots[.]txt'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRssDotxmlRoute = ApiRssDotxmlRouteImport.update({
  id: '/api/rss.xml',
  path: '/api/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobotsDottxtRoute = ApiRobotsDottxtRouteImport.update({
  id: '/api/robots.txt',
  path: '/api/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/prompts': typeof PromptsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/rss.xml': typeof ApiRssDotxmlRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/prompts': typeof PromptsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/rss.xml': typeof ApiRssDotxmlRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/prompts': typeof PromptsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/rss.xml': typeof ApiRssDotxmlRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/prompts'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/robots.txt'
    | '/api/rss.xml'
    | '/api/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/prompts'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/robots.txt'
    | '/api/rss.xml'
    | '/api/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/prompts'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/robots.txt'
    | '/api/rss.xml'
    | '/api/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  PromptsRoute: typeof PromptsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiRobotsDottxtRoute: typeof ApiRobotsDottxtRoute
  ApiRssDotxmlRoute: typeof ApiRssDotxmlRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rss.xml': {
      id: '/api/rss.xml'
      path: '/api/rss.xml'
      fullPath: '/api/rss.xml'
      preLoaderRoute: typeof ApiRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/robots.txt': {
      id: '/api/robots.txt'
      path: '/api/robots.txt'
      fullPath: '/api/robots.txt'
      preLoaderRoute: typeof ApiRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  PromptsRoute: PromptsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiRobotsDottxtRoute: ApiRobotsDottxtRoute,
  ApiRssDotxmlRoute: ApiRssDotxmlRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
